### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by vjeux** [GlitterOrg/pipeline#12]
Just wanted to say that I'm SUPER excited about this :) Thanks for driving this effort, I've been waiting for it for so long! Heck, I [ditched CSS](https://speakerdeck.com/vjeux/react-css-in-js), [reimplemented css layout](https://github.com/facebook/css-layout) and [a dom](https://www.youtube.com/watch?v=7rDsRXj9-cU) to workaround those limitations!

**Comment by bfgeek** [comment]
Thanks Christopher! We are pretty excited about the space here. This work is also being standardized within the w3c, as part of a join task force between CSSWG & TAG. If you interested in keeping up with the standardization efforts subscribe to public-houdini@w3.org. 

We just had an initial meeting in Sydney, where we begun outlining what needs to be worked on. You can see the meeting minutes in the IRC Logs here: https://wiki.css-houdini.org/planning/sydney-2015#irc-logs

Feel free to reach out to me personally (ikilpatrick@chromium.org) if you've got any other questions.

Ian
